name: Docker Compose Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'NuvemBack/**'
      - 'pasta/**'
      - 'docker-compose.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "DB_HOST=db" >> .env
          echo "DB_USER=cab" >> .env
          echo "DB_PASS=vm-pass" >> .env
          echo "DB_NAME=site_restaurantes" >> .env
          echo "DB_PORT=3306" >> .env
          echo "MYSQL_ROOT_PASSWORD=password" >> .env
          echo "MYSQL_DATABASE=site_restaurantes" >> .env
          echo "MYSQL_USER=cab" >> .env
          echo "MYSQL_PASSWORD=vm-pass" >> .env

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start containers
        run: |
          docker-compose pull
          docker-compose up -d --build

      - name: Check running containers
        run: docker-compose ps

      - name: Check container logs
        run: |
          docker-compose logs app
          docker-compose logs db