version: '3'
services:
  app:
    image: node:21
    volumes:
      - ./NuvemBack:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "cd NuvemBack && npm install && npm start"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db  # Use 'db' as the MySQL service name
      - DB_USER=cab  # Username defined for MySQL
      - DB_PASS=vm-pass  # Password defined for MySQL
      - DB_NAME=site_restaurantes  # The database name to connect to
      - DB_PORT=3306  # MySQL port
    depends_on:
      - db  # Ensure the db service starts before the app

  db:
    image: mysql:8.0 # Using the latest MySQL image
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password  # Root password for MySQL
      MYSQL_DATABASE: site_restaurantes  # The database name to create
      MYSQL_USER: cab  # Username for MySQL
      MYSQL_PASSWORD: vm-pass  # Password for the new user
    ports:
      - "3307:3306"  # Expose MySQL port
    volumes:
      - db_data:/var/lib/mysql  # Persist data using a volume
      - ./pasta:/docker-entrypoint-initdb.d
volumes:
  db_data:
